apiVersion: v1
kind: Deployment 
metadata:
  name: mini-project-deployment
  labels:
    app: java
spec:
  replicas: 3
  matchlabels:
    label:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      conatainer:
        image: maroof49/test_prod:7
        
