apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-alb-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:<account-id>:certificate/<certificate-id> # optional, for HTTPS
spec:
  rules:
    - host: devopsbymaroof.shop   # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-app-service   # Must match your Service name
                port:
                  number: 80           # Must match your Service port
